# Generated by Django 3.0.5 on 2021-03-17 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210317_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
