# Generated by Django 3.0.5 on 2021-03-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210317_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='move',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
