# Generated by Django 3.0.5 on 2021-03-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210319_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
